Model api
actris-cloudnet/data-processing pull request #12
Opened 2020-10-17 15:25 UTC by tukiains

This PR adds `/modelData/` PUT route to Cloudnet API for adding model files into dataportal.

2020-10-21 12:04 UTC, lakka requested changes
Commitit ok.

Testejä kaivataan lisää, katso kommentit.

Koodin laatu yleisesti ottaen hyvää, muista olla riittävän verboosi muuttujien ja funktioiden nimeämisessä.

2020-10-22 06:42 UTC, tukiains commented on scripts/run-data-submission-api.py
> +@app.post("/modelData/")
Joo näistä olisi hyvä sopia yhdessä.

2020-10-22 06:45 UTC, tukiains commented on src/data_processing/data_submission_api.py
> +            raise HTTPException(status_code=400, detail=f"Invalid model netCDF file: {meta['filename']}")
En ole useinkaan varma oikeasta virhekoodista. On hyvä olla konsistentti, joten voin laittaa tähän 422.

2020-10-22 06:48 UTC, tukiains commented on scripts/run-data-submission-api.py
> +    model_api.save_file_to_temp(file)
En halua tässä vaiheessa kirjoittaa yli olemassa olevia tiedostoja. Jos samanniminen tiedosto lähetetään uudelleen ja siinä on virheitä, menetetään alkuperäinen file. Nyt metadata tutkitaan ennen fileen siirtämistä lopulliseen paikkaan, mikä on turvallisempaa.

2020-10-22 07:16 UTC, tukiains commented on src/test_utils/utils.py
> +def kill_pid(name='data-processing'):
Joo totta tämä on huono, eikä se taida edes toimia niin kuin pitää. Ärsyttävä juttu kun tuo prosessi jää tuonne taustalle pyörimään testien ajamisen jälkeen. Yritän miettiä, jotain parempaa ratkaisua sen tappamiseen explisiittisesti.

2020-10-22 11:36 UTC, tukiains commented on scripts/run-data-submission-api.py
> +    api.update_metadata_status_to_processed(url)
Joo, muutin huonon toiseen huonoon. Tuo `dataportal_url` voisi olla hyvä.

2020-10-22 11:56 UTC, tukiains commented on scripts/run-data-submission-api.py
> +    url = api.create_url(meta)
`create_metadata_url` on hyvä.

2020-10-22 12:05 UTC, tukiains commented on tests/e2e/model_data_submission/tests.py
> +        assert os.stat(link).st_size == FILESIZE
Lisäsin muutaman yksikkötestin samaan tyyliin kuin `test_data_submission_api.py` tiedostossa tehdään.

2020-10-22 12:05 UTC, tukiains commented on src/data_processing/data_submission_api.py
> +        raise HTTPException(status_code=500, detail=f"File saving failed: {full_path}")
Mietitään tätä jos palvelu on tulossa laajemminkin käyttöön.

2020-11-13 12:40 UTC, tukiains commented
Tämä toteutettiinkin suoraan data portaalissa.

2020-11-13 12:40 UTC, closed without merging